# This workflow will build the python package, and publish it to PyPI.
# https://docs.github.com/en/actions/tutorials/build-and-test-code/python#publishing-to-pypi

name: Python Publish
on:
  workflow_run:
    workflows: ["Python Pytest"]
    types: [completed]
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    name: Build Distribution
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    outputs:
      pkginfo_version: ${{ steps.pkginfo.outputs.version }}
      taginfo_tagname: ${{ steps.taginfo.outputs.tagname }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 65535 # Full branch history (or at least most of it)

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        run: pip install uv

      - name: Build Package
        env:
          BUILD: "" # Set build version to nothing => Offical release
        run: uv build

      - name: Readout package info
        id: pkginfo
        run: |
          version=$(uv tool run pkginfo --single -f version dist/*.tar.gz)
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Set tag info
        id: taginfo
        env:
          TAGNAME: v${{ steps.pkginfo.outputs.version }}
          MESSAGE: ""
        run: |
          echo "tagname=${TAGNAME}" >> "$GITHUB_OUTPUT"
          echo "message=${MESSAGE}" >> "$GITHUB_OUTPUT"

      - name: Tag build
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.taginfo.outputs.tagname }}
          message: ${{ steps.taginfo.outputs.message }}

      - name: Upload Tarball (Source) Distribution
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

      - name: Upload Wheel Distribution
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl

  publish-github:
    name: Publish Distribution as Github Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v5

      - name: Retrieve Tarball (Source) Distribution
        uses: actions/download-artifact@v5
        with:
          name: sdist
          path: dist/

      - name: Retrieve Wheel Distribution
        uses: actions/download-artifact@v5
        with:
          name: wheel
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.taginfo_tagname }}
          files: |
            dist/*
